let quotes = [
  "Mogambo khush hua!",
  "Aree o Sambha, kitne aadmi the?",
  "Kya aap close-up karte hain?",
  "Babu Rao, mast hai!",
  "Kitne aadmi the? Ek, do, teen, char...",
  "Don ko pakadna mushkil hi nahin, namumkin hai.",
  "Tension lene ka nahi, dene ka!",
  "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
  "Aao, kabhi haveli pe!",
  "Hum ek baar jeete hain, ek baar marte hain, shaadi bhi ek baar hoti hai, aur pyar... ek hi baar hota hai.",
  "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
  "Bade bade logon mein aisi chhoti chhoti baatein hoti rehti hai, Babuji.",
  "Teja main hoon, mark idhar hai!",
  "Yeh toh purani ho gayi!",
  "Ek chutki sindoor ki keemat tum kya jaano, Ramesh babu?",
  "Ja Simran, jee le apni zindagi!",
  "Haan, main lut gaya!",
  "Mere paas maa hai.",
  "Thappad se darr nahi lagta sahab, pyar se lagta hai.",
  "Mujhe yeh rishta pasand nahi aaya!",
  "Tumhara naam kya hai, Basanti?",
  "Mere Karan-Arjun aayenge!",
  "Yeh kya ho raha hai, Bhai?",
  "Rishte mein toh hum tumhare baap lagte hain, naam hai Shahenshah.",
  "Itna sannata kyun hai, bhai?",
  "Ek machhar aadmi ko hijda bana deta hai.",
  "Life mein teen cheez kabhi underestimate nahi karna - I, Me, and Myself.",
  "Aaj ek burger khayenge, aaj ek pizza khayenge, aaj ek chocolate shake piyenge, aur aaj ke baad dieting shuru!",
  "Dil garden garden ho gaya.",
  "Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bus rukna nahi chahta.",
  "Insaan ka emotion uska motion hota hai.",
  "I can talk English, I can walk English, I can laugh English because English is a very funny language.",
  "Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho.",
  "Life mein kuch bhi ho sakta hai, aur agar kuch nahi ho sakta toh kuch bhi kyun karein?",
  "Jahanpanah, tussi great ho!",
  "Aisa toh aadmi life mein doich time bhaagta hai... Olympic ka race ho, yaa police ka case ho.",
  "Kutte, kameene, main tera khoon pee jaoonga!",
  "Hera pheri mein kuch bhi ho sakta hai!",
  "Yeh aapke saath kaise hua?",
  "Choli ke peeche kya hai?",
  "Kya tumhe yakeen hai?",
  "Iss desi bade dilwale ki duniya mein aadmi sirf do hi cheezon se jeeta hai, ya toh pyar mein ya phir... war mein!",
  "Bhaisaab, hum masala dosa aur vada pav ke bina kaise ji sakte hain?",
  "Kuch toh log kahenge, logo ka kaam hai kehna.",
  "Ek baar commitment kar di toh phir main apne aap ki bhi nahi sunta.",
  "Jab tak cinema hall mein rahega, log ch****ya banate rahenge.",
  "Aal izz well!",
  "Tension nahi leneka, sirf dene ka!",
  "Goli nahi maarenge, saale ko goli se uda denge!",
  "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
  "Why so serious? - The Dark Knight",
  "I'm the king of the world! - Titanic",
  "You talking to me? - Taxi Driver",
  "Houston, we have a problem. - Apollo 13",
  "You can't handle the truth! - A Few Good Men",
  "You can't sit with us! - Mean Girls",
  "I'll be back. - The Terminator",
  "I coulda been a contender. - On the Waterfront",
  "Here's looking at you, kid. - Casablanca",
  "To infinity and beyond! - Toy Story",
  "I see dead people. - The Sixth Sense",
  "Just keep swimming. - Finding Nemo",
  "You are not alone. - Superman",
  "Keep your friends close, but your enemies closer. - The Godfather Part II",
  "You had me at 'hello.' - Jerry Maguire",
  "Show me the money! - Jerry Maguire",
  "There's no crying in baseball! - A League of Their Own",
  "You are a toy! - Toy Story 2",
  "Why don't you come up sometime and see me? - She Done Him Wrong",
  "You've got to ask yourself one question: 'Do I feel lucky?' Well, do you, punk? - Dirty Harry",
  "I'm not bad. I'm just drawn that way. - Who Framed Roger Rabbit",
  "I'm just one stomach flu away from my goal weight. - The Devil Wears Prada",
  "My mama always said life was like a box of chocolates. You never know what you're gonna get. - Forrest Gump",
  "They've done studies, you know. 60% of the time, it works every time. - Anchorman",
  "You're killing me, Smalls! - The Sandlot",
  "I'm not a smart man, but I know what love is. - Forrest Gump",
  "I'm in a glass case of emotion! - Anchorman",
  "I feel pretty, oh so pretty! - West Side Story",
  "There's no place like home. - The Wizard of Oz",
  "It's alive! - Frankenstein",
  "I am Groot. - Guardians of the Galaxy",
  "A martini. Shaken, not stirred. - Goldfinger",
  "Nobody puts Baby in a corner. - Dirty Dancing",
  "Well, nobody's perfect. - Some Like It Hot",
  "You complete me. - Jerry Maguire",
  "I've got a bad feeling about this. - Star Wars",
  "It's not a man purse. It's called a satchel. - The Hangover",
  "I'm flying, Jack! - Titanic",
  "I'm just a girl, standing in front of a boy, asking him to love her. - Notting Hill",
  "I see you. - Avatar",
  "If you build it, he will come. - Field of Dreams",
  "This is the start of a beautiful friendship. - Casablanca",
  "It's a trap! - Star Wars: Return of the Jedi",
  "I have nipples, Greg. Could you milk me? - Meet the Parents",
  "I'm gonna make him an offer he can't refuse. - The Godfather",
  "What we've got here is failure to communicate. - Cool Hand Luke",
  "There is no spoon. - The Matrix",
  "I'm as mad as hell, and I'm not going to take this anymore! - Network",
  "These go to eleven. - This Is Spinal Tap",
  "I cannot tell a lie, I did it with my little hatchet. - George Washington",
  "I came, I saw, I conquered. - Julius Caesar",
  "I am not a crook. - Richard Nixon",
  "I have nothing to offer but blood, toil, tears, and sweat. - Winston Churchill",
  "I may be drunk, Miss, but in the morning I will be sober, and you will still be ugly. - Winston Churchill",
  "Behind every great man, there is a woman rolling her eyes. - Jim Carrey",
  "I'm writing a book. I've got the page numbers done. - Steven Wright",
  "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character. - Martin Luther King Jr.",
  "I was born at a very young age. - Groucho Marx",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "I can resist everything except temptation. - Oscar Wilde",
  "I have taken more out of alcohol than alcohol has taken out of me. - Winston Churchill",
  "The trouble with the world is that it's always one drink behind. - Humphrey Bogart",
  "The only mystery in life is why the kamikaze pilots wore helmets. - Al McGuire",
  "I told my wife she was drawing her eyebrows too high. She looked surprised. - Unknown",
  "I'm on the whisky diet. I've lost three days already. - Tommy Cooper",
  "I'm writing a letter. I can't write a letter. Why can't I write a letter? I'm breathing, eating, sleeping, walking, talking a letter. But I can't write a letter. - Ernest Hemingway",
  "I like work: it fascinates me. I can sit and look at it for hours. - Jerome K. Jerome",
  "I used to be Snow White, but I drifted. - Mae West",
  "If you're going through hell, keep going. - Winston Churchill",
  "My doctor gave me six months to live, but when I couldn't pay the bill, he gave me six months more. - Walter Matthau",
  "I can resist everything except temptation. - Oscar Wilde",
  "Don't be so humble, you're not that great. - Golda Meir",
  "I've had a perfectly wonderful evening, but this wasn't it. - Groucho Marx",
  "I'm not crazy; my mother had me tested. - Sheldon Cooper (The Big Bang Theory)",
  "You can lead a horse to water, but a pencil must be led. - Stan Laurel",
  "I'm not arguing, I'm just explaining why I'm right. - Unknown",
  "I used to jog, but the ice cubes kept falling out of my glass. - David Lee Roth",
  "I don't want to achieve immortality through my work. I want to achieve it through not dying. - Woody Allen",
  "I'm so clever that sometimes I don't understand a single word of what I'm saying. - Oscar Wilde",
  "You can do anything, but not everything. - David Allen",
  "Behind every great man, there is a woman rolling her eyes. - Jim Carrey",
  "The trouble with being punctual is that nobody's there to appreciate it. - Franklin P. Jones",
  "I'm writing a book. I've got the page numbers done. - Steven Wright",
  "I'm writing a letter. I can't write a letter. Why can't I write a letter? I'm breathing, eating, sleeping, walking, talking a letter. But I can't write a letter. - Ernest Hemingway",
  "I like work: it fascinates me. I can sit and look at it for hours. - Jerome K. Jerome",
  "I used to be Snow White, but I drifted. - Mae West",
  "The only mystery in life is why the kamikaze pilots wore helmets. - Al McGuire",
  "My doctor gave me six months to live, but when I couldn't pay the bill, he gave me six months more. - Walter Matthau",
  "I can resist everything except temptation. - Oscar Wilde",
  "Don't be so humble, you're not that great. - Golda Meir",
  "I've had a perfectly wonderful evening, but this wasn't it. - Groucho Marx",
  "I'm not arguing, I'm just explaining why I'm right. - Unknown",
  "I'm not crazy; my mother had me tested. - Sheldon Cooper (The Big Bang Theory)",
  "You can lead a horse to water, but a pencil must be led. - Stan Laurel",
  "I'm not arguing, I'm just explaining why I'm right. - Unknown",
  "I used to jog, but the ice cubes kept falling out of my glass. - David Lee Roth",
  "I don't want to achieve immortality through my work. I want to achieve it through not dying. - Woody Allen",
  "I'm so clever that sometimes I don't understand a single word of what I'm saying. - Oscar Wilde",
  "You can do anything, but not everything. - David Allen",
  "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
  "There are only 10 types of people in the world: those who understand binary and those who don't.",
  "I would love to change the world, but they won't give me the source code.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "Why don't programmers like nature? It has too many bugs.",
  "Programming is like sex: one mistake and you have to support it for the rest of your life.",
  "Software developers are the only people who will answer 'yes' to 'Is the glass half empty or half full?' by saying, 'It depends on the type of glass and the requirements.'",
  "A SQL query walks into a bar, walks up to two tables and asks, 'Can I join you?'",
  "Why do Java developers wear glasses? Because they don't see sharp.",
  "Real programmers count from 0.",
  "Why don't programmers play hide and seek? Because good players are hard to find.",
  "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
  "Algorithm: Word used by programmers when they do not want to explain what they did.",
  "I'm not a great programmer; I'm just a good programmer with great habits.",
  "The three most dangerous things in the world are a programmer with a soldering iron, a hardware engineer with a software patch, and a user with an idea.",
  "In software, we rarely have meaningful requirements. The best we can hope for is a list of odd demands.",
  "The code that is the hardest to debug is the code that you know cannot possibly be wrong.",
  "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.",
  "If at first, you don't succeed, call it version 1.0.",
  "The best performance improvement is the transition from the nonworking state to the working state.",
  "It's not a bug – it's an undocumented feature.",
  "Software is like sex; it's better when it's free.",
  "I'm not anti-social; I'm just not user-friendly.",
  "It's not a computer bug; it's a computer feature!",
  "Programming is the art of telling another human being what one wants the computer to do.",
  "The computer was born to solve problems that did not exist before.",
  "In software development, there are two types of people: those who have lost data and those who will.",
  "A user interface is like a joke. If you have to explain it, it's not that good.",
  "The best way to predict the future is to implement it.",
  "Documentation is like sex; when it's good, it's very, very good, and when it's bad, it's better than nothing.",
  "There are only two hard things in computer science: cache invalidation and naming things.",
  "It's not a codebase; it's a jungle.",
  "I'm not saying it's Microsoft's fault. I'm just saying that they have a lot of problems for a company that wants to help you solve yours.",
  "Programming is like kicking yourself in the head with a golf shoe.",
  "A programmer is a person who fixed a problem that you don't know you have, in a way you don't understand.",
  "I don't always test my code, but when I do, I do it in production.",
  "You know you're a programmer when you spend more time reading error messages than actual code.",
  "Programmers don't die; they just go offline.",
  "It works on my machine.",
  "I'm not a programmer; I'm a software developer. There's a difference.",
  "Code is like humor. When you have to explain it, it's bad.",
  "If brute force doesn't solve your problems, then you're not using enough.",
  "Programming is easy, like riding a bike. Except the bike is on fire, you're on fire, everything is on fire, and you're in hell.",
  "The code you write today is the legacy code of tomorrow.",
  "I don't write bugs; I just create random unexpected features.",
  "Why do Java developers wear glasses? Because they don't C#!",
  "I don't need a girlfriend; I have a code editor.",
  "The Internet: where men are men, women are men, and children are FBI agents.",
  "Programmers don't make mistakes; we just create unexpected features.",
  "Code never lies; comments sometimes do.",
  "Programming is the art of doing one thing 99 times in a slightly different way each time.",
  "There are 10 types of people in the world: those who understand binary, those who don't, and those who weren't expecting this joke to be in base 3.",
  "Welcome to Jurassic Park. - John Hammond",
  "Life, uh, finds a way. - Dr. Ian Malcolm",
  "Clever girl... - Robert Muldoon",
  "Hold on to your butts. - Ray Arnold",
  "They're moving in herds. They do move in herds. - Dr. Alan Grant",
  "I'm always on the lookout for the future ex-Mrs. Malcolm. - Dr. Ian Malcolm",
  "Dinosaurs and man, two species separated by 65 million years of evolution... just been suddenly thrown back into the mix together. How can we have the slightest idea what to expect? - Dr. Ian Malcolm",
  "What do they got in there, King Kong? - Dr. Ian Malcolm",
  "That's one big pile of s***. - Dr. Ian Malcolm",
  "Must go faster! - Dr. Ian Malcolm",
  "Dinosaur eats man. Woman inherits the Earth. - Dr. John Hammond",
  "You're implying that a group composed entirely of female animals will... breed? No, I'm simply saying that life, uh, finds a way. - Dr. Ian Malcolm",
  "Spared no expense. - John Hammond",
  "I don't want to jump to any conclusions, but look... dinosaurs and man, two species separated by 65 million years of evolution, just been suddenly thrown back into the mix together. How can we possibly have the slightest idea what to expect? - Dr. Ian Malcolm",
  "We have all the problems of a major theme park and a major zoo, and the computers aren't even on their feet yet. - John Hammond",
  "Don't be scared. Come on, it's okay. She's sick. We're going to take care of you, okay? - Dr. Ellie Sattler",
  "Dennis, our lives are in your hands, and you have butterfingers? - Donald Gennaro",
  "You think they'll have that on the tour? - Dr. Alan Grant",
  "You're supposed to come down here and defend me against these characters, and the only one I've got on my side is the blood-sucking lawyer! - John Hammond",
  "Are these characters autoerotic? - Dr. Ian Malcolm",
  "Remind me to thank John for a lovely weekend. - Dr. Ellie Sattler",
  "I thought you were one of your big brothers. You're not so bad. - Lex Murphy",
  "We're gonna make a fortune with this place. - Dr. John Hammond",
  "We're going to open next year. That is if the lawyers don't kill me first. - John Hammond",
  "I am totally unappreciated in my time. You can run this whole park from this room with minimal staff for up to three days. - Dennis Nedry",
  "I think we're back in business. - Dr. Ellie Sattler",
  "I'm, I'm simply saying that life, uh... finds a way. - Dr. Ian Malcolm",
  "It's, it's a, it's a dinosaur. - Dr. John Hammond",
  "Yeah, yeah, but your scientists were so preoccupied with whether or not they could that they didn't stop to think if they should. - Dr. Ian Malcolm",
  "Don't you see the danger, John, inherent in what you're doing here? Genetic power is the most awesome force the planet's ever seen, but you wield it like a kid that's found his dad's gun. - Dr. Ian Malcolm",
  "It's a Unix system, I know this! - Lex Murphy",
  "They're just, they're just animals, for Christ's sake! - Dr. Ellie Sattler",
  "Yesterday, December 7, 1941, a date which will live in infamy... - Franklin D. Roosevelt",
  "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender. - Winston Churchill",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "I fear all we have done is to awaken a sleeping giant and fill him with a terrible resolve. - Isoroku Yamamoto",
  "Never in the field of human conflict was so much owed by so many to so few. - Winston Churchill",
  "This is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning. - Winston Churchill",
  "We will not tire, we will not falter, and we will not fail. - George W. Bush",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
  "In war, there are no unwounded soldiers. - José Narosky",
  "In the Soviet army, it takes more courage to retreat than to advance. - Joseph Stalin",
  "The Germans wore gray, you wore blue. - James M. McPherson",
  "I don't know what effect these men will have upon the enemy, but, by God, they terrify me. - Duke of Wellington",
  "In war, the way is to avoid what is strong and to strike at what is weak. - Sun Tzu",
  "The true soldier fights not because he hates what is in front of him, but because he loves what is behind him. - G.K. Chesterton",
  "All wars are civil wars because all men are brothers. - François Fénelon",
  "Nuts! - General Anthony McAuliffe",
  "The only thing that ever consoles man for the stupid things he does is the praise he always gives himself for doing them. - Oscar Wilde",
  "Don't fight a battle if you don't gain anything by winning. - Erwin Rommel",
  "I have nothing to offer but blood, toil, tears, and sweat. - Winston Churchill",
  "Freedom is not free. - Anonymous",
  "Never was so much owed by so many to so few. - Winston Churchill",
  "No bastard ever won a war by dying for his country. You win a war by making the other poor dumb bastard die for his country. - General George S. Patton",
  "The battle of Iwo Jima has been won. Among the Americans who served on Iwo Island, uncommon valor was a common virtue. - Chester W. Nimitz",
  "We will not flag or fail. We shall go on to the end. We shall fight in France, we shall fight on the seas and oceans",
  "The secret ingredient is always love.",
  "Cooking is an art, but all art requires knowing something about the techniques and materials.",
  "Food is symbolic of love when words are inadequate.",
  "The only time to eat diet food is while you're waiting for the steak to cook.",
  "Good food is the foundation of genuine happiness.",
  "There is no sincerer love than the love of food.",
  "People who love to eat are always the best people.",
  "Cooking is like love. It should be entered into with abandon or not at all.",
  "The kitchen is the heart of the home.",
  "Food brings people together on many different levels. It's the nourishment of the soul and body; it's truly love.",
  "If you're afraid of butter, use cream.",
  "Life is too short for self-hatred and celery sticks.",
  "The smell of good bread baking, like the sound of lightly flowing water, is indescribable in its evocation of innocence and delight.",
  "Cooking is not difficult. Everyone has taste, even if they don't realize it. Even if you're not a great chef, there's nothing to stop you from understanding the difference between what tastes good and what doesn't.",
  "Food is our common ground, a universal experience.",
  "Grilling is a form of cooking that involves dry heat applied to the surface of food, commonly from above, below, or from the side.",
  "A recipe has no soul. You, as the cook, must bring soul to the recipe.",
  "To me, life without veal stock, pork fat, sausage, organ meat, demi-glace, or even stinky cheese is a life not worth living.",
  "Food is the most primitive form of comfort.",
  "When you have only two pennies left in the world, buy a loaf of bread with one, and a lily with the other.",
  "Cooking is about passion, so it may look slightly temperamental in a way that it's too assertive to the naked eye.",
  "When in doubt, eat chaat.",
  "Life is better with a plate of pani puri.",
  "Samosa: The original pocket-friendly snack.",
  "Street food is the heart and soul of India.",
  "Aloo Tikki: A taste of India's streets.",
  "Spicy, crispy, and oh so delicious!",
  "Chaat: A burst of flavors in every bite.",
  "Kebabs that melt in your mouth.",
  "Dosa: A South Indian delight.",
  "Vada Pav: The Indian burger.",
  "Street food is the real comfort food.",
  "Golgappa cravings are real.",
  "Paneer Tikka: Vegetarian heaven.",
  "Tandoori momos: A fusion of flavors.",
  "Chole Bhature: A North Indian favorite.",
  "Street food vendors are culinary artists.",
  "Pav Bhaji: Mumbai's magic on a plate.",
  "Eating street food is like a culinary adventure.",
  "Bhel Puri: A burst of textures and flavors.",
  "Kachori: A spicy indulgence.",
  "Street food: Where hunger meets happiness.",
  "Sev Puri: The perfect bite-sized snack.",
  "Momos with chutney: A match made in heaven.",
  "Vibrant, flavorful, and affordable.",
  "Pakoras: Rainy day comfort food.",
  "Street food vendors are the unsung heroes of taste.",
  "Chai and samosa: A classic combination.",
  "Biryani by the roadside: Pure bliss.",
  "Treat yourself to some Indian street food.",
  "Jalebi: Sweetness in every swirl.",
  "Street food is the ultimate soul food.",
  "Kathi rolls: A street food sensation.",
  "Bhelpuri: The original snackable salad.",
  "Taste the diversity of India on the streets.",
  "Street food: A feast for the senses.",
  "Chaiwala: Serving warmth in a cup.",
  "Paratha rolls: A culinary marvel.",
  "Kulfi: India's frozen dessert delight.",
  "Street food is the heart of Indian culture.",
  "Pav Bhaji: A symphony of flavors.",
  "Seekh kebabs: Grill perfection.",
  "Street food is where traditions come alive.",
  "Dabeli: A spicy and sweet surprise.",
  "Street food: The best way to explore India.",
  "Chai and gossip: A street food ritual.",
  "Mouthwatering and unforgettable.",
  "Street food: A carnival for your taste buds.",
  "Poha: A breakfast favorite on the streets.",
  "Indian street food: Where cravings find satisfaction.",
  "Savor the magic of Indian street food.",
  "The best way to predict the future is to create it. - Peter Drucker",
  "The more you learn, the more you earn. - Warren Buffett",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "The secret to getting ahead is getting started. - Mark Twain",
  "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "I never dreamed about success. I worked for it. - Estée Lauder",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Success is not just about making money. It's about making a difference. - Unknown",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs. - Zig Ziglar",
  "The only wealth which you will keep forever is the wealth you have given away. - Marcus Aurelius",
  "The greatest wealth is to live content with little. - Plato",
  "Formal education will make you a living; self-education will make you a fortune. - Jim Rohn",
  "The more you give, the more comes back to you. - Napoleon Hill",
  "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought, and so broadens the mind. - T.T. Munger",
  "The goal isn't more money. The goal is living life on your terms. - Chris Brogan",
  "The only wealth I see is life. - Henry David Thoreau",
  "A wise man should have money in his head, but not in his heart. - Jonathan Swift",
  "Don't wait for opportunity. Create it. - Unknown",
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "Money is a terrible master but an excellent servant. - P.T. Barnum",
  "The stock market is filled with individuals who know the price of everything, but the value of nothing. - Philip Fisher",
  "The best investment you can make is in yourself. - Warren Buffett",
  "The key to making money is to stay invested. - Suze Orman",
  "I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy. - Warren Buffett",
  "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
  "The four most dangerous words in investing are: 'This time it's different.' - Sir John Templeton",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas. - Paul Samuelson",
  "In investing, what is comfortable is rarely profitable. - Robert Arnott",
  "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
  "The most important quality for an investor is temperament, not intellect. You need a temperament that neither derives great pleasure from being with the crowd or against the crowd. - Warren Buffett",
  "The goal of a successful trader is to make the best trades. Money is secondary. - Alexander Elder",
  "The four most dangerous words in investing are: 'This time it's different.' - Sir John Templeton",
  "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
];

export { quotes };
